### ISSUE TITLE
Mélangeur

### ISSUE THREAD

**Issue by MRossignol** [MRossignol/ticel#1]
J'ouvre ce fil de discussion afin de discuter et préciser les fonctionnalités du mixeur. Tout d'abord, d'un point de vue organisationnel, je dois préciser que le développement de cette fonction est un travail conséquent (un mois ou deux, en comptant le temps nécessaire pour discuter et préciser le fonctionnement exact) qui va de ce fait dépasser le cadre du contrat initial de développement du site. La description initiale de cette fonction n'étant pas absolument claire, et celle-ci n'ayant pas été mentionnée de nouveau depuis les premiers jours du projet, j'avais à vrai dire supposé que l'idée en avait été abandonnée...

Pour lancer la discussion, voici la description initialement proposée par Yan :

Le mélangeur permet d'entendre une superposition de plusieurs sons de la base de données.
Le mélangeur serait une sorte d'espace de « n » sphères, ou chaque sphère représente l'espace de variation applicable au son sélectionné autour de deux axes. Le son serait lui représenté comme un point dans cette sphère.
En déplaçant par exemple le son -à l'aide du point- simultanément dans 2 axes correspondant à la hauteur et aux modes de jeux, nous pouvons choisir la position finale de l'instrument 1 du mélangeur. Après validation, l'utilisateur peut additionner le deuxième son, et ainsi de suite.
L’utilisateur doit pouvoir sauver sous la forme d’un fichier son le résultat de son mélange.

**Comment by MRossignol** [comment]
Je m'interroge sur la faisabilité d'une représentation dans l'espace 2D du choix de la technique et de la hauteur :
- concernant la technique, il n'y a pas d'ordre numérique "naturel" des techniques, je crains donc que la représentation ne soit pas très intuitive. On pourrait de manière alternative imaginer une sélection par menu radial autour du point représentant le son/instrument, par exemple.
- concernant la hauteur, c'est plus anecdotique mais je crains que la représentation ne soit pas très lisible (ni très "maniable") pour les instruments à large tessiture... à voir.

Finalement, il faudrait sans doute également prévoir que l'interface permette de représenter et manipuler la dynamique, non ?

**Comment by zseramnay** [comment]
L'idée de le sphère était de pousser un peu plus loin l'exploration des sons à l'aide d'un interface dédiée. Certes, ce n'était pas très clair au premier jet...

Mais je pense que nous pouvons nous concentrer sur quelque chose de beaucoup plus simple qui permettrait toutefois à l'utilisateur d'entendre plusieurs sons superposés. Ce serait un mélangeur de base.
-Idéalement depuis la page du son, envoi vers le mélangeur.
-page du mélangeur: ce peut être une liste des sons avec un bouton play/stop/save (et peut-être un slider de mix pour chaque son( pour corriger d'éventuelles erreurs de niveau individuels)

**Comment by MRossignol** [comment]
Mélangeur simple implémenté, avec sliders de volume et possibilité de décaler temporellement les samples.
