### ISSUE TITLE
Gestion des samples pour les techniques à multiple paramètres

### ISSUE THREAD

**Issue by MRossignol** [MRossignol/ticel#2]
L'organisation de la base de données du site Ticel a été développée en se basant sur les exemples disponibles initialement, à savoir les enregistrements de flûte, d'une part, et la base SOL, utilisée comme référence, d'autre part. L'organisation déduite de ces exemples est donc instrument -> technique -> hauteur (ou équivalent) -> dynamique. Au vu des propositions faites pour l'organisation des nouveaux intruments ajoutés en ces derniers mois du projet (Ondes Martenot, accordéon), il semble nécessaire de "faire rentrer" des paramètres supplémentaires, parfois spécifiques à l'instrument, dans cette base.

Deux solutions semblent alors possibles :
1. modifier le stockage et la présentation des techniques afin de rendre celles-ci arborescentes, de la même manière que ce qui est fait actuellement pour les instruments. Par exemple, si je comprends bien la combinaison de paramètres pour les Ondes Martenot, quelque chose comme ceci pourrait être possible :
- ordinaire
  - ordinaire bague
    - ordinaire bague d1d3d4+5
      - ordinaire bague d1d3d4+5-8+4
      - ordinaire bague d1d3d4+5-8+5
    - ordinaire bague d1d3d4+3
      - ordinaire bague d1d3d4+3-8+4
      - ordinaire bague d1d3d4+3-8+5
  - ordinaire clavier
    - ordinaire clavier d1d3d4+5
      - ordinaire clavier d1d3d4+5-8+4
      - ordinaire clavier d1d3d4+5-8+5
    - ordinaire clavier d1d3d4+3
      - ordinaire clavier d1d3d4+3-8+4
      - ordinaire clavier d1d3d4+3-8+5
etc.

2. Ajouter comme le propose Étienne Graindorge dans son email du 13 janvier la possibilité d'ajouter des critères d'indexation "custom" adaptés à chaque instrument.

La première solution peut être intégrée au site existant avec un peu d'effort, compatible avec une "amélioration" dans le cadre du développement actuel ; sans être la plus élégante, elle présente l'avantage de permettre à un visiteur non spécialiste de visualiser facilement l'ensemble des samples présents dans la base, en dépliant simplement l'arborescence.

La seconde solution demande un travail considérable de refonte en profondeur du schéma de la base de données, ainsi que de l'interface de présentation des sons ; elle requiert de plus le développement d'outils significativement plus complexes pour l'introduction et l'édition des entrées. J'estime de ce fait qu'elle dépasse le cadre du contrat de développement actuel.

Je vous propose de discuter ci-dessous afin de trouver une solution satisfaisante.

**Comment by egraindorge** [comment]
Je comprends que le boulot de refonte de la base soit conséquent, et peut-être faut-il le garder en tête pour une prochaine phase d'améliorations en fonction des premiers retours sur expérience...
Pour la proposition d'une arborescence, si je comprends bien c'est quelque chose qui sera totalement automatisé ? c'est à dire que l'arborescence se créera directement après une analyse de la liste de sons fournis ? Ou alors faut-il décider d'un nombre de sous rubriques ?
Ensuite une autre question serait : est-il possible de mettre une description automatique du son dans lequel les noms de fichiers sont décodés ?
C'est particulièrement utile pour les ondes martenot où on ne peut pas deviner quel haut-parleur est d3, mais pour tous les autres instruments, les noms des modes de jeu sont abrégés également

**Comment by MRossignol** [comment]
Finalement, l'option de techniques arborescentes était peu élégante à l'usage. J'ai donc intégré la possibilité d'intégrer lors de l'ajout de samples de nouveaux critères d'indexation, en définissant un schéma de nom de fichier spécifique. L'interface de sélection des samples permet de choisir dans quel ordre les critères sont parcourus : par exemple, on peut choisir la note en premier puis voir quels types de sons sont disponibles pour celle-ci, ou à l'inverse spécifier d'abord les critères de texture sonore puis voir quelles notes sont disponibles pour ceux-ci.
