### ISSUE TITLE
Pages d'introduction "statiques" éditables

### ISSUE THREAD

**Issue by MRossignol** [MRossignol/ticel#3]
Il a été demandé lors de la réunion du 12 janvier d'avoir la possibilité d'ajouter des pages d'information générale accessibles directement depuis la page d'accueil et dont les administrateurs puissent éditer le contenu. Cela demande l'introduction de nouvelles fonctionnalités assez conséquentes, non prévues dans le design actuel :
- accès à des pages sans contrôle d'identité de l'utilisateur,
- mise au point d'un design pour ces pages sortant du format à base de cadres utilisé pour le site actuel,
- intégration d'un éditeur de contenu en ligne suivant ce design.

Je vous invite à discuter ci-dessous des modalités selon lesquelles cela peut-être ajouté au projet.

**Comment by zseramnay** [comment]
nous anticipions le fait qu'une ou plusieurs pages statiques puissent avoir besoin d'être intégrées dans le futur..
page de crédits par exemple ou de specs d'enregistrement des samples, etc..
la liste de ces sous pages pourraient apparaitre dans un petit menu qui serait lié à une icône supplémentaire ?

**Comment by MRossignol** [comment]
Fonction ajoutée.
